# Generated by Django 3.2.3 on 2021-07-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_registro_colab_registrocolab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('contraseña', models.CharField(max_length=100, verbose_name='Contraseña')),
            ],
        ),
        migrations.DeleteModel(
            name='registrocolab',
        ),
    ]
